-- SQL para crear la tabla de participantes en Supabase
-- Ejecutar en el SQL Editor de Supabase

CREATE TABLE IF NOT EXISTS clientes (
    nit TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS participantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL,
    factura TEXT UNIQUE NOT NULL,
    piloto TEXT NOT NULL,
    nit TEXT REFERENCES clientes(nit),
    telefono TEXT,
    empresa TEXT,
    consumo TEXT,
    premio TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS empresas (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    nit TEXT,
    manager TEXT,
    phone TEXT,
    email TEXT,
    server TEXT,
    code TEXT UNIQUE,
    logo TEXT, -- Base64 o URL
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS premios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_code TEXT NOT NULL,
    tier TEXT NOT NULL, -- 'general', 'plata', 'oro'
    prizes JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(empresa_code, tier)
);

CREATE TABLE IF NOT EXISTS configuraciones (
    clave TEXT PRIMARY KEY,
    valor_inicio TEXT, -- Para fechas
    valor_fin TEXT,    -- Para fechas
    valor_oro NUMERIC,
    valor_plata NUMERIC,
    valor_general NUMERIC,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar permisos públicos (Solo para desarrollo, en producción usar RLS)
ALTER TABLE empresas DISABLE ROW LEVEL SECURITY;
ALTER TABLE premios DISABLE ROW LEVEL SECURITY;
ALTER TABLE configuraciones DISABLE ROW LEVEL SECURITY;
